name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.5.3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip
          python -m pip install --upgrade pip
          pip install Cython virtualenv

      - name: Set up buildozer environment
        uses: ArtemSBulgakov/buildozer-action@v1

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3.5.3
        with:
          name: app-debug.apk
          path: bin/*.apk
